import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./data/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#534434",
        background: "#0b1326",
        "error-container": "#93000a",
        "on-surface": "#dae2fd",
        "surface-container-lowest": "#060e20",
        "surface-bright": "#31394d",
        tertiary: "#f5c80c",
        surface: "#0b1326",
        "primary-fixed": "#ffddb8",
        "inverse-surface": "#dae2fd",
        "tertiary-fixed-dim": "#eec200",
        primary: "#ffc174",
        "primary-container": "#f59e0b",
        "tertiary-fixed": "#ffe083",
        "on-secondary-fixed": "#410004",
        "secondary-fixed-dim": "#ffb3ad",
        "surface-container-highest": "#2d3449",
        "tertiary-container": "#d5ad00",
        error: "#ffb4ab",
        "surface-container-low": "#131b2e",
        "inverse-on-surface": "#283044",
        "surface-container-high": "#222a3d",
        "on-primary-container": "#613b00",
        "primary-fixed-dim": "#ffb95f",
        "surface-tint": "#ffb95f",
        "on-secondary": "#68000a",
        "on-tertiary-fixed-variant": "#574500",
        "on-secondary-container": "#ffaea8",
        "secondary-container": "#a40217",
        outline: "#a08e7a",
        "on-error-container": "#ffdad6",
        "on-background": "#dae2fd",
        "secondary-fixed": "#ffdad7",
        "surface-container": "#171f33",
        "surface-variant": "#2d3449",
        "on-primary-fixed": "#2a1700",
        "inverse-primary": "#855300",
        "on-surface-variant": "#d8c3ad",
        "on-tertiary-fixed": "#231b00",
        "on-tertiary-container": "#534200",
        "surface-dim": "#0b1326",
        secondary: "#ffb3ad",
        "on-secondary-fixed-variant": "#930013",
        "on-tertiary": "#3c2f00",
        "on-primary-fixed-variant": "#653e00",
        "on-primary": "#472a00",
        "on-error": "#690005",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "container-max": "1280px",
        gutter: "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "display-lg": ["Sora"],
        "body-md": ["Hanken Grotesk"],
        "label-sm": ["JetBrains Mono"],
        "headline-lg": ["Sora"],
        "body-lg": ["Hanken Grotesk"],
        "headline-md": ["Sora"],
        "headline-lg-mobile": ["Sora"],
        "label-md": ["JetBrains Mono"],
      },
      fontSize: {
        "display-lg": [
          "72px",
          {
            lineHeight: "80px",
            letterSpacing: "-0.04em",
            fontWeight: "800",
          },
        ],
        "body-md": [
          "16px",
          { lineHeight: "24px", fontWeight: "400" },
        ],
        "label-sm": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.1em",
            fontWeight: "500",
          },
        ],
        "headline-lg": [
          "48px",
          {
            lineHeight: "56px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", fontWeight: "400" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "40px", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "40px", fontWeight: "700" },
        ],
        "label-md": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0.05em",
            fontWeight: "500",
          },
        ],
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-20px)" },
        },
        orbital: {
          "0%, 100%": { transform: "translateY(0) translateX(0)" },
          "33%": { transform: "translateY(-15px) translateX(10px)" },
          "66%": { transform: "translateY(10px) translateX(-15px)" },
        },
        "pulse-glow": {
          "0%, 100%": { opacity: "0.4" },
          "50%": { opacity: "0.8" },
        },
        "gradient-shift": {
          "0%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        orbital: "orbital 12s infinite ease-in-out",
        "pulse-glow": "pulse-glow 4s ease-in-out infinite",
        "gradient-shift": "gradient-shift 8s ease infinite",
      },
    },
  },
  plugins: [],
};
export default config;
